### ISSUE TITLE
Can bypass CloudFlare, DDoS-Guard, Sucuri or other WAF/Anti-DDoS?

### ISSUE THREAD

**Issue by darkanubis0100** [wildonion/thedos#1]

**Comment by wildonion** [comment]
I think so, I didn't try to run against them. This stage has a basic http request which implemented from the HULK idea and a single-ip-single-port attack on TCP and UDP.
Currently I'm working on the proxy feature to cover yourself every few seconds to avoid blocking issues by them.
Also pull requests are welcome ✌️ && <3

**Comment by darkanubis0100** [comment]
Oh!

Interesting. Although I don't know "cargo" and specifically the programming language you use in the .rs files.

What language is it?

**Comment by wildonion** [comment]
The Rust programming language, it’s fast and memory and thread safety by its design. cargo is the package manger of that and the whole attacking part is based on the tokio framework which is used for the multi threading part since it has green threads like the Go language which uses goroutines

**Comment by darkanubis0100** [comment]
One more question...

What is the URL of "Cargo"? https://cargo.build? I can't seem to see any kind of installer or installation instructions.

**Comment by wildonion** [comment]
You can install the Rust from [here ](https://www.rust-lang.org/tools/install) and cargo will be installed automatically. Also the package manager link is https://crates.io
